### ISSUE TITLE
Time Issue?

### ISSUE THREAD

**Issue by webosa** [anand-p-r/hslhrt-hass-custom#10]
Hi first, thanks for this genius integration, much appreciated. However I noticed some weird time issue on one stop E1030.

Time for the next route shows 1 day, 2:10:00 .. however the bus is scheduled for 02:10. Why the "1 Day"?

![2021-01-25 01_49_03-Home - Home Assistant – Mozilla Firefox](https://user-images.githubusercontent.com/16862797/105647715-33b9c600-5eb0-11eb-91eb-2304c39f96bc.png)
![2021-01-25 01_49_25-Pysäkki - Läkkisepänkuja E1030 – Mozilla Firefox](https://user-images.githubusercontent.com/16862797/105647716-36b4b680-5eb0-11eb-8266-1536554e9af7.png)

**Comment by anand-p-r** [comment]
Hi @webosa 
Thanks for trying this out!
There was  bug in arrival time calculation in UI and it is fixed in [latest release](https://github.com/anand-p-r/hslhrt-hass-custom/releases/tag/v2.1). Can you give it a shot and let me know if it fixes the "1 day...." display issue?
