### ISSUE TITLE
Installation with latest HA version (2022.3.1)

### ISSUE THREAD

**Issue by sla004** [anand-p-r/hslhrt-hass-custom#18]
Hi,

When I try to add integration from integration list I get 500 error message.

Anyone else having same problem?

**Comment by samhaa** [comment]
> Hi,
> 
> When I try to add integration from integration list I get 500 error message.
> 
> Anyone else having same problem?

I have same problem.

**Comment by Jazzi0** [comment]
Not sure if this is related, but I get following error when upgraded to homeassistant 2022.3.{1/2/3} (all ready installed hslhrt on earlier version of homeassistant)
```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: March 6, 2022, 8:06:14 PM (1 occurrences)
Last logged: March 6, 2022, 8:06:14 PM

Setup failed for custom integration hslhrt: Requirements for hslhrt not found: ['python_graphql_client==0.3.1'].

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: March 6, 2022, 8:06:07 PM (3 occurrences)
Last logged: March 6, 2022, 8:06:14 PM

Unable to install package python_graphql_client==0.3.1: ERROR: Cannot install python-graphql-client==0.3.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by anand-p-r** [comment]
@sla004 @Jazzi0 @samhaa Please update with the latest [release](https://github.com/anand-p-r/hslhrt-hass-custom/releases/tag/v0.3.5) and see if this fixes the issue.

**Comment by sla004** [comment]
yes, problem solved! Thanks @anand-p-r
